---
version: 2.1

jobs:
  git-leaks:
    machine:
      image: ubuntu-2204:2022.07.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Scan for gitLeaks
          command: |
            docker run \
              -v ~/repo:/path zricethezav/gitleaks:latest \
              detect --source="/path" -v
  yamllint:
    docker:
      - image: python@sha256:$CIRCLE_PYTHON_IMAGE_SHA
    resource_class: small
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Ubuntu packages
          command: |
            export DEBIAN_FRONTEND='noninteractive'
            apt-get update
            apt-get install -y yamllint
      - run:
          name: Lint repo with yamllint
          command: |
            cd ~/repo
            yamllint .
  pytest:
    machine:
      image: ubuntu-2204:2022.07.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ checksum "~/repo/.circleci/demo/requirements.txt" }}
      - run:
          name: Install Python dependencies
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            python3 -m pip install -U pip flake8 wheel setuptools
            pip install -r ~/repo/.circleci/demo/requirements.txt
      - save_cache:
          key: deps1-{{ checksum "~/repo/.circleci/demo/requirements.txt" }}
          paths:
            - ".venv"
      - run:
          name: Run tests
          command: |
            . .venv/bin/activate
            python -m pytest ~/repo/.circleci/demo/main.py \
              --html-report=./test-results
      - store_artifacts:
          path: ~/repo/test-results
          destination: unittest-results
  flake8:
    docker:
      - image: python@sha256:$CIRCLE_PYTHON_IMAGE_SHA
    resource_class: small
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: Flake8-{{ .Environment.FLAKE8 }}
      - run:
          name: Install Flake8
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip install flake8 flake8-html
      - save_cache:
          key: Flake8-{{ .Environment.FLAKE8 }}
          paths:
            - ".venv"
      - run:
          name: Run Flake8 against repo
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            cd ~/repo/.circleci/demo
            python3 -m flake8 . \
              --count --select=E901,E999,F821,F822,F823 \
              --show-source --statistics --format=html \
              --htmldir=flake-report
            python3 -m flake8 . --count --exit-zero \
              --max-complexity=10 --max-line-length=127 \
              --statistics --format=html --htmldir=flake-report
      - store_artifacts:
          path: ~/repo/.circleci/demo/flake-report
          destination: flake-report
workflows:
  untagged_builds:
    jobs:
      - git-leaks
      - yamllint
      - pytest
      - flake8
