---
version: 2.1

jobs:
  git-leaks:
    machine:
      image: ubuntu-2204:2022.07.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Scan for gitLeaks
          command: |
            docker run -v ~/repo:/path zricethezav/gitleaks:latest detect --source="/path" -v

workflows:
  say-hello-workflow:
    jobs:
      - git-leaks
