name: docker image build 
on: push

jobs:
  docker-create:
    runs-on: ubuntu-latest
    environment: testing 
    steps:
      - uses: actions/checkout@v4
      - name: docker login 
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build docker image 
        run: |
          docker build -t aspdotnet .
          docker tag aspdotnet keagan123456/aspdotnet:latest
          docker push keagan123456/aspdotnet:latest
        shell: bash